import type { TurnReviewScenario } from "./types";

export const DEMO_TURN_REVIEW: TurnReviewScenario = {
  id: "turn-review-running-shoe-promo",
  title: "Running-shoe promotion turn review",
  situation:
    "An AI agent proposes a 20% promotional move for STR-001 Classic Runner after finding margin room and seasonal demand. Choose the turn before any write happens.",
  proposedMoveId: "move-controlled-promo",
  defaultSelectedMoveId: "move-controlled-promo",
  board: [
    {
      id: "margin-pressure",
      label: "Margin pressure",
      value: 68,
      state: "review",
      note: "Discount fits the floor, but leaves little room for stacking.",
    },
    {
      id: "inventory-exposure",
      label: "Inventory exposure",
      value: 46,
      state: "review",
      note: "Single SKU has enough stock for a limited test.",
    },
    {
      id: "customer-comms-blast-radius",
      label: "Customer comms blast radius",
      value: 72,
      state: "blocked",
      note: "Broad messaging would spread the change before learning.",
    },
    {
      id: "rollback-confidence",
      label: "Rollback confidence",
      value: 82,
      state: "cleared",
      note: "Promo flag and price field can be rehearsed before approval.",
    },
  ],
  moves: [
    {
      id: "move-aggressive-promo",
      kind: "aggressive",
      label: "Execute broad promo now",
      oneLine: "Apply the 20% promo across the running group and notify shoppers.",
      policyState: "blocked",
      blastRadius: 88,
      reversibility: 42,
      evidenceStrength: 54,
      timeToLearn: "Same day",
      operatorCost: "High: approval, comms review, rollback watch",
      regret: {
        ifChosen: "If margin assumptions are wrong, many shoppers see a noisy price correction.",
        ifRejected: "You may miss a short demand window for the running group.",
      },
      rollback: {
        available: true,
        steps: [
          "Turn promo flags off for affected synthetic SKUs.",
          "Clear promo prices back to blank fields.",
          "Send an internal receipt note for manual comms review.",
        ],
        residualRisk: "Customer-facing comms may already have copied the broader offer.",
      },
      receiptPreview: {
        receiptId: "trn-prev-001-aggressive",
        chosenMoveId: "move-aggressive-promo",
        policyDecision: "blocked: broad promo plus comms blast radius",
        approvalMode: "Escalated approval required before any write",
        rollbackAvailable: true,
        auditLabel: "synthetic-turn/aggressive/broad-promo",
      },
    },
    {
      id: "move-controlled-promo",
      kind: "controlled",
      label: "Run limited promo with approval",
      oneLine: "Activate 20% on STR-001 only, gated by approval and receipt preview.",
      policyState: "review",
      blastRadius: 48,
      reversibility: 78,
      evidenceStrength: 83,
      timeToLearn: "24 hours",
      operatorCost: "Medium: one approval and one rollback rehearsal",
      regret: {
        ifChosen: "If demand is weak, one SKU carries the test cost and can be reversed cleanly.",
        ifRejected: "You lose the strongest useful evidence without reducing much risk.",
      },
      rollback: {
        available: true,
        steps: [
          "Restore STR-001 promo active to false.",
          "Clear STR-001 promo price.",
          "Attach policy and approval result to the synthetic receipt.",
        ],
        residualRisk: "Small merchandising confusion if the offer is copied elsewhere manually.",
      },
      receiptPreview: {
        receiptId: "trn-prev-002-controlled",
        chosenMoveId: "move-controlled-promo",
        policyDecision: "review: single SKU write with margin guardrail",
        approvalMode: "Step-up approval before synthetic write simulation",
        rollbackAvailable: true,
        auditLabel: "synthetic-turn/controlled/str-001-promo",
      },
    },
    {
      id: "move-scout-check",
      kind: "scout",
      label: "Scout with read-only check",
      oneLine: "Do not write; verify price, stock, and margin assumptions first.",
      policyState: "cleared",
      blastRadius: 18,
      reversibility: 96,
      evidenceStrength: 67,
      timeToLearn: "1 hour",
      operatorCost: "Low: review findings before the next turn",
      regret: {
        ifChosen: "You delay the promo, but learn whether the write is still safe.",
        ifRejected: "You may approve with stale inventory or margin evidence.",
      },
      rollback: {
        available: false,
        steps: [],
        residualRisk: "No write occurs, so rollback is not needed.",
      },
      receiptPreview: {
        receiptId: "trn-prev-003-scout",
        chosenMoveId: "move-scout-check",
        policyDecision: "cleared: read-only scout",
        approvalMode: "No approval needed for read-only synthetic check",
        rollbackAvailable: false,
        auditLabel: "synthetic-turn/scout/read-only-check",
      },
    },
    {
      id: "move-defensive-block",
      kind: "defensive",
      label: "Block and require manual review",
      oneLine: "Stop the turn until an operator confirms margin and comms constraints.",
      policyState: "review",
      blastRadius: 28,
      reversibility: 90,
      evidenceStrength: 45,
      timeToLearn: "Next review cycle",
      operatorCost: "Medium: manual check and a new turn decision",
      regret: {
        ifChosen: "You avoid execution risk, but the demand signal may expire.",
        ifRejected: "You accept more automation risk than the current evidence supports.",
      },
      rollback: {
        available: false,
        steps: [],
        residualRisk: "No write occurs; opportunity cost is the main residual risk.",
      },
      receiptPreview: {
        receiptId: "trn-prev-004-defensive",
        chosenMoveId: "move-defensive-block",
        policyDecision: "review: blocked by operator choice",
        approvalMode: "Manual review required before a future turn",
        rollbackAvailable: false,
        auditLabel: "synthetic-turn/defensive/manual-review",
      },
    },
  ],
};
